repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    - id: black
      language_version: python3.11