[theme]
# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "monospace"

# https://discuss.streamlit.io/t/why-do-default-values-cause-a-session-state-warning/15485/33
[global]
disableWidgetStateDuplicationWarning = true
